[package]
name = "tts-service"
version = "0.1.0"
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "thin"

[dependencies]
deadpool-redis = "0.11"
parking_lot = "0.12"
serde_json = "1"
once_cell = "1"
tracing = "0.1"
sha2 = "0.10"
anyhow = "1"
cfg-if = "1"
bytes = "1"

[dependencies.fernet]
version = "0.2"
features = ["rustcrypto"]
default-features = false

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["smallvec", "fmt", "ansi", "parking_lot"]

[dependencies.axum]
version = "0.6"
default-features = false
features = ["http1", "http2", "json", "query", "tokio"]

[dependencies.tokio]
version = "1"
features = ["sync", "time", "macros", "rt-multi-thread", "parking_lot", "signal"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.redis]
version = "0.22"
default-features = false
features = ["aio", "tokio-comp"]

[dependencies.rand]
version = "0.8"
optional = true

[dependencies.reqwest]
version = "0.11"
features = ["rustls-tls"]
default-features = false
optional = true

[dependencies.base64]
version = "0.21"
optional = true

[dependencies.ipgen]
version = "1"
optional = true

[dependencies.jsonwebtoken]
version = "8"
optional = true

[dependencies.espeakng]
version = "0.1"
optional = true

[dependencies.mp3-duration]
version = "0.1"
optional = true

[dependencies.itertools]
version = "0.10"
optional = true

[dependencies.aws-sdk-polly]
version = "0.24.0"
optional = true

[dependencies.aws-config]
version = "0.54.0"
optional = true

[features]
gtts = ["rand", "reqwest", "ipgen", "mp3-duration", "itertools"]
gcloud = ["reqwest", "reqwest/json", "jsonwebtoken", "base64"]
espeak = ["tokio/process", "tokio/io-util", "espeakng"]
polly = ["aws-sdk-polly", "aws-config"]

default = ["espeak"]
