[package]
name = "tts-service"
version = "0.1.0"
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "thin"

[dependencies]
tracing-subscriber = "0.3"
parking_lot = "0.12"
serde_json = "1"
tracing = "0.1"
bytes = "1"

[dependencies.axum]
version = "0.4"
default-features = false
features = ["http1", "json"]

[dependencies.tokio]
version = "1"
features = ["sync", "time", "macros", "rt-multi-thread", "parking_lot"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.rand]
version = "0.8"
optional = true

[dependencies.reqwest]
version = "0.11"
optional = true

[dependencies.base64]
version = "0.13"
optional = true

[dependencies.ipgen]
version = "1"
optional = true

[dependencies.jsonwebtoken]
version = "8"
optional = true

[dependencies.espeakng]
version = "0.1.1"
optional = true


[features]
premium = ["reqwest", "reqwest/json", "jsonwebtoken", "base64"]
espeak = ["tokio/process", "tokio/io-util", "espeakng"]
gtts = ["rand", "reqwest", "ipgen"]

default = ["espeak"]
