[package]
name = "gtts-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "thin"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
axum = "0.4"
rand = "0.8"
reqwest = "0.11"
parking_lot = "0.12"
ipgen = "1"

axum-macros = "0.1"

[dependencies.tokio]
version = "1"
features = ["sync", "time", "macros", "rt-multi-thread", "parking_lot"]

[dependencies.serde]
version = "1"
features = ["derive"]
